version: "3.1"
services:
    project-service:
        image: workingwithprojectsapi:dev
        container_name: project-service
        ports:
            - "8000:80"
        depends_on:
            - db
        restart: on-failure
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"